CREATE DATABASE IF NOT EXISTS `mongo_results` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
DROP TABLE IF EXISTS `mongo_results`.`stadistics_result`;
CREATE TABLE `mongo_results`.`stadistics_result` (
`grouped` INT(10),
`result` FLOAT(10),
`type_grouped` VARCHAR(255)
);
LOAD DATA LOCAL INFILE 'result/stadistics_result.csv' INTO TABLE `mongo_results`.`stadistics_result` FIELDS TERMINATED BY ','  ENCLOSED BY '"' IGNORE 1 LINES;
DROP TABLE IF EXISTS `mongo_results`.`sample_0-01`;
CREATE TABLE `mongo_results`.`sample_0-01` (
`HECHO` VARCHAR(255),
`RUPTURA` VARCHAR(255),
`CONEXO` VARCHAR(255),
`ESTADO_NOTICIA` VARCHAR(255),
`ETAPA` VARCHAR(255),
`ANIO_DENUNCIA` INT(10),
`ANIO_ENTRADA` INT(10),
`ANIO_HECHO` INT(10),
`LEY` VARCHAR(255),
`PAIS` VARCHAR(255),
`DEPARTAMENTO` VARCHAR(255),
`MUNICIPIO` VARCHAR(255),
`SECCIONAL` VARCHAR(255),
`GRUPO_DELITO` VARCHAR(255),
`DELITO` VARCHAR(255),
`IMPUTACION` VARCHAR(255),
`CONDENA` VARCHAR(255),
`ATIPICIDAD_INEXISTENCIA` VARCHAR(255),
`ACUSACION` VARCHAR(255),
`CAPTURA` VARCHAR(255),
`SEXO_INDICIADO` VARCHAR(255),
`GRUPO_EDAD_INDICIADO` VARCHAR(255),
`PAIS_NACIMIENTO` VARCHAR(255),
`HOMICIDIO_DOLOSO_CONSUMADO` VARCHAR(255),
`TOTAL_INDICIADOS` INT(10)
);
LOAD DATA LOCAL INFILE 'result/sample_0-01.csv' INTO TABLE `mongo_results`.`sample_0-01` FIELDS TERMINATED BY ','  ENCLOSED BY '"' IGNORE 1 LINES;
DROP TABLE IF EXISTS `mongo_results`.`sample_0-01_filtered`;
CREATE TABLE `mongo_results`.`sample_0-01_filtered` (
`HECHO` VARCHAR(255),
`RUPTURA` VARCHAR(255),
`CONEXO` VARCHAR(255),
`ESTADO_NOTICIA` VARCHAR(255),
`ETAPA` VARCHAR(255),
`ANIO_DENUNCIA` INT(10),
`ANIO_ENTRADA` INT(10),
`ANIO_HECHO` INT(10),
`LEY` VARCHAR(255),
`PAIS` VARCHAR(255),
`DEPARTAMENTO` VARCHAR(255),
`MUNICIPIO` VARCHAR(255),
`SECCIONAL` VARCHAR(255),
`GRUPO_DELITO` VARCHAR(255),
`DELITO` VARCHAR(255),
`IMPUTACION` VARCHAR(255),
`CONDENA` VARCHAR(255),
`ATIPICIDAD_INEXISTENCIA` VARCHAR(255),
`ACUSACION` VARCHAR(255),
`CAPTURA` VARCHAR(255),
`SEXO_INDICIADO` VARCHAR(255),
`GRUPO_EDAD_INDICIADO` VARCHAR(255),
`PAIS_NACIMIENTO` VARCHAR(255),
`HOMICIDIO_DOLOSO_CONSUMADO` VARCHAR(255),
`TOTAL_INDICIADOS` INT(10)
);
LOAD DATA LOCAL INFILE 'result/sample_0-01_filtered.csv' INTO TABLE `mongo_results`.`sample_0-01_filtered` FIELDS TERMINATED BY ','  ENCLOSED BY '"' IGNORE 1 LINES;
